compilers:
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@7.5.0
- compiler:
    spec: intel@19.1.1.217
    paths:
      cc: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/bin/intel64/icc
      cxx: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/bin/intel64/icpc
      f77: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/bin/intel64/ifort
      fc: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      set:
        INTEL_LICENSE_FILE: 28518@128.117.177.41
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux/lib/intel64
    extra_rpaths: []
- compiler:
    spec: nvhpc@21.7
    paths:
      cc: /glade/u/apps/opt/nvhpc/21.7/Linux_x86_64/21.7/compilers/bin/nvc
      cxx: /glade/u/apps/opt/nvhpc/21.7/Linux_x86_64/21.7/compilers/bin/nvc++
      f77: /glade/u/apps/opt/nvhpc/21.7/Linux_x86_64/21.7/compilers/bin/nvfortran
      fc: /glade/u/apps/opt/nvhpc/21.7/Linux_x86_64/21.7/compilers/bin/nvfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      set:
        NVLOCALRC: /glade/u/apps/opt/nvhpc/21.7/localrc/crayenv
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/opt/nvhpc/21.7/Linux_x86_64/21.7/compilers/lib
    extra_rpaths: []
- compiler:
    spec: cce@13.0.1
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-cray
    - cce/13.0.1
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/8.1.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/10.3.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.2.0
    environment: {}
    extra_rpaths: []
