packages:
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  gcc:
    externals:
    - spec: gcc@7.5.0 languages=c,c++
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++-7
    compiler: [gcc@7.5.0]
    variants: [+piclibs, 'languages=c,c++,fortran,go']
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
  libfuse:
    externals:
    - spec: libfuse@3.6.1
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.1p1
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.5.9
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
    buildable: false
  automake:
    externals:
    - spec: automake@1.15.1
      prefix: /usr
    buildable: false
  cpio:
    externals:
    - spec: cpio@2.12
      prefix: /usr
    buildable: false
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
    buildable: false
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /usr
    buildable: false
  ghostscript:
    externals:
    - spec: ghostscript@9.52
      prefix: /usr
    buildable: false
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
    buildable: false
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
  openssl:
    externals:
    - spec: openssl@1.1.1d
      prefix: /usr
    buildable: false
  perl:
    externals:
    - spec: perl@5.26.1~cpanm+shared+threads
      prefix: /usr
    buildable: false
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
    buildable: false
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
    buildable: false
  all:
    'compiler:': [gcc@7.5.0, gcc, cce, nvhpc, intel]
    providers:
      'mpi:': [cray-mpich, openmpi]
      'szip:': [libszip]
      'pkgconfig:': [pkg-config]
    permissions:
      read: world
      write: user
  cuda:
    externals:
    - spec: cuda@11.4.48
      prefix: /glade/u/apps/dav/opt/cuda/11.4.0
    buildable: false
  pbspro:
    externals:
    - spec: pbspro@2021.1.1
      prefix: /opt/pbs
    buildable: false
  intel:
    externals:
    - spec: intel@19.1.1.217%gcc@7.5.0
      prefix: /glade/u/apps/opt/intel/2020u1/compilers_and_libraries/linux
    buildable: false
  nvhpc:
    externals:
    - spec: nvhpc@21.7%gcc@7.5.0
      prefix: /glade/u/apps/opt/nvhpc/21.7/Linux_x86_64/21.7/compilers
    buildable: false
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.13 %gcc
      prefix: /opt/cray/pe/mpich/8.1.13/ofi/gnu/9.1
      modules:
      - cray-mpich/8.1.13
      - craype-network-ofi
    - spec: cray-mpich@8.1.13 %cce
      prefix: /opt/cray/pe/mpich/8.1.13/ofi/cray/10.0
      modules:
      - cray-mpich/8.1.13
      - craype-network-ofi
    - spec: cray-mpich@8.1.13 %nvhpc
      prefix: /opt/cray/pe/mpich/8.1.13/ofi/nvidia/20.7
      modules:
      - cray-mpich/8.1.13
      - craype-network-ofi
    buildable: false
  cray-fftw:
    externals:
    - spec: cray-fftw@3.3.8.12
      modules:
      - cray-fftw/3.3.8.12
    buildable: false
  cray-libsci:
    externals:
    - spec: cray-libsci@21.08.1.2
      modules:
      - cray-libsci/21.08.1.2
    buildable: false
  openmpi:
    variants: [+cuda, fabrics=auto, schedulers=tm]
  netcdf:
    variants: [+dap, -mpi]
  netcdf-c:
    variants: [+dap, -mpi]
  hdf5:
    variants: [+hl, +szip, +fortran, +cxx, -mpi]
  netcdf-cxx4:
    variants: [-doxygen]
  fftw:
    variants: [-mpi]
  eccodes:
    variants: [+fortran, +netcdf, +png, jp2k=jasper]
  curl:
    variants: [tls=gnutls]
